/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Puppy: typeof import('./src/components/Puppy.vue')['default']
    PuppyChatCard: typeof import('./src/components/PuppyChatCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    Woofle: typeof import('./src/components/Woofle.vue')['default']
    WoofleCard: typeof import('./src/components/WoofleCard.vue')['default']
    WoofleFooter: typeof import('./src/components/WoofleFooter.vue')['default']
  }
}
